Задание
sashakboo/orpiweb pull request #1
Opened 2021-09-10 05:58 UTC by sashakboo

2021-09-24 04:58 UTC, coffeek commented
Почему-то у меня ничего не подгружается - висит Loading:
![image](https://user-images.githubusercontent.com/829589/134620621-fde6c92e-5ecd-4487-b216-661987fb41c7.png)

2021-09-24 04:59 UTC, coffeek commented
Раз уж мы тут на неткор все переходим, переведи плиз проект сервера на .Net Core WebAPI

2021-09-24 05:06 UTC, coffeek requested changes
Надо поправить по замечаниям

2021-09-24 05:06 UTC, coffeek commented on Server/WebServer/WebServer.csproj
>      <UseGlobalApplicationHostFile />
Раз уж мы тут на неткор все переходим, переведи плиз проект сервера на .Net Core WebAPI

2021-09-24 05:06 UTC, coffeek commented on Server/WebServer/Controllers/ProductsController.cs
> +﻿using System.Collections.Generic;
Оформи код бекенда по стандарту плиз. Добавь в корень исходников сервера .editorconfig из репы Sungero - студия сразу всё подсветит, что надо поменять

2021-09-24 05:06 UTC, coffeek commented on Server/WebServer/ProductsService.cs
> +  public class ProductsService
Как только переведёшь проект под netcore, можно этот класс будет зарегать как сервис в контейнере и подсовывать контроллеру в конструкторе, как остальные сервисы (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0)

2021-09-24 05:06 UTC, coffeek commented on Server/WebServer/ProductsService.cs
> +      lock (syncRoot)
По идее надо ставить блокировку не только на добавление в корзину, но и на чтение, т.к. данные хранятся в обычном списке и в теории если корзиной будут пользоваться несколько пользователей одновременно, может быть ошибка. А вообще лучше заиспользовать какой-нибудь ConcurrentDictionary вместо списков

2021-09-30 05:44 UTC, sashakboo commented on Server/WebServer/ProductsService.cs
> +      lock (syncRoot)
Прикрутил БД

2021-09-30 05:44 UTC, sashakboo commented on Server/WebServer/ProductsService.cs
> +  public class ProductsService
Перевел

2021-09-30 05:45 UTC, sashakboo commented on Server/WebServer/WebServer.csproj
>      <UseGlobalApplicationHostFile />
Перевел

2021-09-30 05:45 UTC, sashakboo commented on Server/WebServer/Controllers/ProductsController.cs
> +﻿using System.Collections.Generic;
Поправил

2021-10-04 11:33 UTC, coffeek approved these changes
Всё отлично

2021-10-05 09:06 UTC, merged